name: plaza_prelim_project
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.18.0 <3.0.0"

# Add regular dependencies here.
dependencies:
  riverpod: ^2.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
